org: happyboy
app: gitme
service: gitme

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-east-2

  # Notes: useless not working, I will have to manually: 
  # Notes: remove the client file -> 'sls deploy' on the terminal -> bring the file back 
  # package:
  #   individually: true
  #   exclude:
  #     - ./*


functions:
  api:
    # handler: handler.handler
    # events:
    #   - http:
    #       path: /
    #       method: ANY
    #   - http:
    #       path: /{proxy+}
    #       method: ANY

    handler: server.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
    
